- name: Identity and Access Management 
  shortName: iam
  description: |
    Manage access to HiiRetail services and resources securely.
    Using IAM, you can create tenants and setup identity providers, manage users and groups,
    and use permissions to allow and deny their access to resources.
  coverImage: todo
  tags:
    - iam
    - permission
    - group
    - role
    - user
    - identity

