name: IAM Sync Functions                                     
shortName: iam-functions                                 
description: | 
  IAM Sync Functions are triggered at different steps of
  auth flow, for example - sync name from federated platform, before user signs in.
rootDoc: index.md                               
tags:                                          
  - iam
